[workspace]

members = [
    "learning",
    "tasks",
    "tokio_async",
    "managing_projects",
    "server_with_standard_library",
    "server_with_tide",
    "server_with_warp",
    "server_with_rocket",
    "server_with_actix",
]
