pub mod fulfilled_types_traits;
pub mod default_common_types_and_operator_overload;
pub mod call_methods_and_functions_with_the_same_name;
pub mod super_traits_and_trait_in_trait;
pub mod new_type_external_crates;
